import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Oxanium } from 'next/font/google';
import Navbar from "../components/custom/navbar";
import { cn } from "@/lib/utils";
import React from "react";

// const inter = Inter({ subsets: ["latin"] });
const oxanium = Oxanium({
  subsets: ['latin'],
  variable: '--font-oxanium',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Problocks",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen bg-white font-sans antialiased overflow-x-hidden",
          oxanium.variable
        )}
      >
        <Navbar />
        <div className="flex flex-col flex-1 h-full">{children}</div>
      </body>
    </html>
  );
}
