const tileGameLevels: TileCommands[][][] = [
  [
    [
      { type: 'connect', start: 'A1', end: 'B1' },
    ],
    [
      { type: 'connect', start: 'A1', end: 'A2' },
    ],
    [
      { type: 'connect', start: 'B2', end: 'C3' },
    ],
    [
      { type: 'connect', start: 'A1', end: 'C3' },
    ],
    [
      { type: 'connect', start: 'B1', end: 'D4' },
    ],
  ],

  [
    [
      { type: 'connect', start: 'A1', end: 'B1' },
      { type: 'connect', start: 'B1', end: 'C1' },
      { type: 'connect', start: 'C1', end: 'D1' },
    ],
    [
      { type: 'connect', start: 'A1', end: 'B2' },
      { type: 'connect', start: 'B2', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'E5' },
    ],
    [
      { type: 'connect', start: 'A1', end: 'B1' },
      { type: 'connect', start: 'B1', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'E1' },
      { type: 'connect', start: 'E1', end: 'F1' },
    ],
    [
      { type: 'connect', start: 'B2', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'C3' },
    ],
    [
      { type: 'connect', start: 'A1', end: 'B2' },
      { type: 'connect', start: 'B2', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'E1' },
      { type: 'connect', start: 'E1', end: 'F2' },
    ],
  ],

  [
    [
      { type: 'connect', start: 'B2', end: 'B3' },
      { type: 'connect', start: 'B3', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'B2' },
    ],
    [
      { type: 'connect', start: 'B2', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'B2' },
    ],
    [
      { type: 'connect', start: 'B2', end: 'B4' },
      { type: 'connect', start: 'B4', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'B2' },
    ],
    [
      { type: 'connect', start: 'C2', end: 'B3' },
      { type: 'connect', start: 'B3', end: 'C4' },
      { type: 'connect', start: 'C4', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'C2' },
    ],
    [
      { type: 'connect', start: 'B2', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'E3' },
      { type: 'connect', start: 'E3', end: 'A3' },
      { type: 'connect', start: 'A3', end: 'B2' },
    ],
  ],

  [
    [
      { type: 'connect', start: 'B2', end: 'B3' },
      { type: 'connect', start: 'B3', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'B2' },
      { type: 'connect', start: 'C3', end: 'C4' },
      { type: 'connect', start: 'C4', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'C3' },
      { type: 'connect', start: 'C2', end: 'D3' },
    ],
    [
      { type: 'connect', start: 'C3', end: 'B2' },
      { type: 'connect', start: 'C3', end: 'D2' },
      { type: 'connect', start: 'C3', end: 'B4' },
      { type: 'connect', start: 'C3', end: 'D4' },
      { type: 'connect', start: 'C3', end: 'A3' },
      { type: 'connect', start: 'C3', end: 'E3' },
      { type: 'connect', start: 'B2', end: 'D4' },
      { type: 'connect', start: 'D2', end: 'B4' },
    ],
    [
      { type: 'connect', start: 'C2', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'C5' },
      { type: 'connect', start: 'C5', end: 'B4' },
      { type: 'connect', start: 'B4', end: 'B3' },
      { type: 'connect', start: 'B3', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'C5' },
      { type: 'connect', start: 'B3', end: 'D3' },
      { type: 'connect', start: 'B4', end: 'D4' },
    ],
    [
      { type: 'connect', start: 'B2', end: 'B3' },
      { type: 'connect', start: 'B3', end: 'B4' },
      { type: 'connect', start: 'C2', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'C4' },
      { type: 'connect', start: 'D2', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'D4' },
      { type: 'connect', start: 'B2', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'D2' },
      { type: 'connect', start: 'B3', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'D3' },
      { type: 'connect', start: 'B4', end: 'C4' },
      { type: 'connect', start: 'C4', end: 'D4' },
      { type: 'connect', start: 'B2', end: 'D4' },
      { type: 'connect', start: 'D2', end: 'B4' },
    ],
    [
      { type: 'connect', start: 'C3', end: 'B2' },
      { type: 'connect', start: 'B2', end: 'A3' },
      { type: 'connect', start: 'A3', end: 'B4' },
      { type: 'connect', start: 'B4', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'E3' },
      { type: 'connect', start: 'E3', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'C3' },
      { type: 'connect', start: 'B2', end: 'D2' },
      { type: 'connect', start: 'A3', end: 'E3' },
      { type: 'connect', start: 'B4', end: 'D4' },
    ],
  ],

  [
    [
      { type: 'connect', start: 'B2', end: 'B5' },
      { type: 'connect', start: 'B5', end: 'E5' },
      { type: 'connect', start: 'E5', end: 'E2' },
      { type: 'connect', start: 'E2', end: 'B2' },
      { type: 'connect', start: 'C3', end: 'C4' },
      { type: 'connect', start: 'C4', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'C3' },
      { type: 'connect', start: 'B2', end: 'E5' },
      { type: 'connect', start: 'B5', end: 'E2' },
      { type: 'connect', start: 'C3', end: 'E3' },
      { type: 'connect', start: 'C4', end: 'E4' },
    ],
    [
      { type: 'connect', start: 'A1', end: 'C3' },
      { type: 'connect', start: 'C3', end: 'E5' },
      { type: 'connect', start: 'E5', end: 'E1' },
      { type: 'connect', start: 'E1', end: 'C3' },
      { type: 'connect', start: 'A5', end: 'C3' },
      { type: 'connect', start: 'A1', end: 'E5' },
      { type: 'connect', start: 'A5', end: 'E1' },
      { type: 'connect', start: 'B2', end: 'D4' },
      { type: 'connect', start: 'B4', end: 'D2' },
      { type: 'connect', start: 'C1', end: 'C5' },
      { type: 'connect', start: 'A3', end: 'E3' },
      { type: 'connect', start: 'C2', end: 'D3' },
      { type: 'connect', start: 'B3', end: 'C4' },
    ],
    [
      { type: 'connect', start: 'C3', end: 'D3' },
      { type: 'connect', start: 'D3', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'C4' },
      { type: 'connect', start: 'C4', end: 'B4' },
      { type: 'connect', start: 'B4', end: 'B3' },
      { type: 'connect', start: 'B3', end: 'B2' },
      { type: 'connect', start: 'B2', end: 'C2' },
      { type: 'connect', start: 'C2', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'E2' },
      { type: 'connect', start: 'E2', end: 'E3' },
      { type: 'connect', start: 'E3', end: 'E4' },
      { type: 'connect', start: 'E4', end: 'E5' },
      { type: 'connect', start: 'E5', end: 'D5' },
      { type: 'connect', start: 'D5', end: 'C5' },
      { type: 'connect', start: 'C3', end: 'E5' },
      { type: 'connect', start: 'B2', end: 'D4' },
      { type: 'connect', start: 'C2', end: 'C4' },
      { type: 'connect', start: 'D2', end: 'B4' },
    ],
    [
      { type: 'connect', start: 'A3', end: 'B2' },
      { type: 'connect', start: 'B2', end: 'C1' },
      { type: 'connect', start: 'C1', end: 'D2' },
      { type: 'connect', start: 'D2', end: 'E3' },
      { type: 'connect', start: 'E3', end: 'D4' },
      { type: 'connect', start: 'D4', end: 'C5' },
      { type: 'connect', start: 'C5', end: 'B4' },
      { type: 'connect', start: 'B4', end: 'A3' },
      { type: 'connect', start: 'A3', end: 'E3' },
      { type: 'connect', start: 'B2', end: 'D4' },
      { type: 'connect', start: 'D2', end: 'B4' },
      { type: 'connect', start: 'C1', end: 'C5' },
      { type: 'connect', start: 'C3', end: 'A3' },
      { type: 'connect', start: 'C3', end: 'B2' },
      { type: 'connect', start: 'C3', end: 'D2' },
      { type: 'connect', start: 'C3', end: 'B4' },
      { type: 'connect', start: 'C3', end: 'D4' },
      { type: 'connect', start: 'C3', end: 'E3' },
    ],
    [
      { type: 'connect', start: 'C3', end: 'B2' },
      { type: 'connect', start: 'C3', end: 'D2' },
      { type: 'connect', start: 'C3', end: 'E3' },
      { type: 'connect', start: 'C3', end: 'D4' },
      { type: 'connect', start: 'C3', end: 'B4' },
      { type: 'connect', start: 'C3', end: 'A3' },
      { type: 'connect', start: 'B2', end: 'A1' },
      { type: 'connect', start: 'D2', end: 'E1' },
      { type: 'connect', start: 'E3', end: 'F4' },
      { type: 'connect', start: 'D4', end: 'E5' },
      { type: 'connect', start: 'B4', end: 'A5' },
      { type: 'connect', start: 'A3', end: 'B5' },
      { type: 'connect', start: 'A1', end: 'E5' },
      { type: 'connect', start: 'E1', end: 'A5' },
      { type: 'connect', start: 'B2', end: 'D4' },
      { type: 'connect', start: 'D2', end: 'B4' },
      { type: 'connect', start: 'A3', end: 'E3' },
      { type: 'connect', start: 'C1', end: 'C5' },
      { type: 'connect', start: 'B3', end: 'D3' },
      { type: 'connect', start: 'C2', end: 'C4' },
    ],
  ],
];

export default tileGameLevels;
